### ISSUE TITLE
Suggestion Sort Horizontal 

### ISSUE THREAD

**Issue by mohcow** [gnwl/NotGrid#18]
would be cool if you could add the option to change way groups are sorted from vertical to horizontal(left to right)

**Comment by gnwl** [comment]
There is the option of "growth direction" in the menu with several styles. It's not very intuitive, you'll just have to change the slider until you find the one you want(turn on config mode as well). It's horizontal by default, though, so not sure if I'm misinterpreting your request.

**Comment by mohcow** [comment]
that's exactly what i wanted. Thank you very much.
