### ISSUE TITLE
Options request.

### ISSUE THREAD

**Issue by Thunderba11** [gnwl/NotGrid#20]
Great addon, been using it for a while. Two requests for options:
1) Option to disable tooltips when over NG frames.
2) Option for center icon and/or frame background.

**Comment by gnwl** [comment]
1. "Disable Mouseover in Combat" disables the tooltip while in combat. I'll change the text for that should I push a new update.
2. Probably not going to happen from me.

**Comment by gnwl** [comment]
rephrased mouseover tooltip option
Center icon is requested in another issue
