### ISSUE TITLE
Crashes entire game

### ISSUE THREAD

**Issue by Section82** [gnwl/NotGrid#23]
I just installed this addon and it looked awesome, but unfortunately, when I go to move the frames, the entire game crashes out :(

I would really love to use this, but can't have my game crashing on me....

**Comment by gnwl** [comment]
Definitely a thing. Though difficult to reproduce consistently. I can drag a million times and not encounter it then randomly get hit with it back to back on reloads. There's a bluetracker post referencing this type of crash resulting from GetPoint data being bad after OnDrag with a client fix for it in TBC. I'm not sure what my solution may be.

**Comment by gnwl** [comment]
Removed ondrag, replaced with positioning menu
