### ISSUE TITLE
Prox error

### ISSUE THREAD

**Issue by NightShadowhawk** [gnwl/NotGrid#27]
getting an error on line 155 of proximity.lua "attempt to index field `?' (a nil value)

	distance = sqrt(((px - ux)/MapScales[v.Continent][v.Zone].x)^2 + ((py - uy)/MapScales[v.Continent][v.Zone].y)^2)

this is line 155 and im not seeing an error

**Comment by NightShadowhawk** [comment]
this also causes random game lag due to error spam

**Comment by awijnands** [comment]
@NightShadowhawk - created a fix for this in PR #28

**Comment by gnwl** [comment]
Due to custom zones, I assume. Merged the pull, and fixed the followup nil error. Should work, though will return out of range in unknown zones. Possibly more, I'm not sure how custom zones affect the whole thing.
