### ISSUE TITLE
the % slider for colour is reversed 

### ISSUE THREAD

**Issue by Meridaw** [gnwl/NotGrid#29]
![image](https://github.com/gnwl/NotGrid/assets/26133646/89ea174c-1919-4e8b-ad98-9dcbc22e8b04)

![image](https://github.com/gnwl/NotGrid/assets/26133646/de7f75f4-ca12-4ece-ac25-9664946ca846)

**Comment by gnwl** [comment]
I guess my fix caused a lot more issues. This being reversed is ideal compared to the alternative for the time being.
