### ISSUE TITLE
decursive

### ISSUE THREAD

**Issue by Meridaw** [gnwl/NotGrid#33]
yo. do you think it's possible to make the /decursive or /run Dcr_Clean(); function from the decursive addon be usable with /ngcast to mouseover clean debuffs on the ng frames?

**Comment by gnwl** [comment]
/run Dcr_Clean(GetMouseFocus().unit)  

Likely works on all unit frames as most, including blizz, store the unitid there. Works on the decursive livelist, too. This obviously won't hook into the spellcast proximity check, but I don't know how many people even know that's a feature.

**Comment by Meridaw** [comment]
brilliant. that is perfect. thank you. it seems to work well with spells also. `/run i=(GetMouseFocus().unit) if i then CastSpellByName("Healing Touch") SpellTargetUnit(i) end`
