### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Meridaw** [gnwl/NotGrid#36]
hi. do you think it is possible to add an indicator and a filter that shows you when the players on your grid target npcs that lack the specific debuff named in the filter? by debuffs, I mostly think of debuffs such as e.g druid faerie fire, warlock curses, paladin Judgement of wisdom. it would be very convenient to use in combination with targettarget macros.

**Comment by gnwl** [comment]
It's possible. But there are a lot of potential headaches around it. So likely never going to happen.
