### ISSUE TITLE
Moving Grid

### ISSUE THREAD

**Issue by Meridaw** [gnwl/NotGrid#37]
i really miss moving the grid on the fly when ever i needed. was this changed to improve performance also? maybe there could be some middle ground approach where a mod condition is met? like not in raid, not in combat, not casting spells etc. i could then drag the grid to move it.

**Comment by gnwl** [comment]
It was to avoid a client bug with dragged frames causing a full client crash as described here: https://github.com/gnwl/NotGrid/issues/23#issuecomment-1693193171

I couldn't find a simple workaround for the way I was handling positioning, didn't see a use case for constantly moving the frames, and supported my desires for pixel-perfect positioning anyway. I can add back in a drag option, but I don't think I'll have a workaround for the bug.

**Comment by Meridaw** [comment]
a drag option sounds good. can't say i noticed this bug happening much. I use to move the grid often. probably mostly when i play healing classes. as it often happens that I want a better view where the grid is positioned.
