### ISSUE TITLE
Feature Request: Additional Grow Direction Options

### ISSUE THREAD

**Issue by karai17** [gnwl/NotGrid#45]
Greetings~ Would it be possible to add a grow direction option that anchors on the bottom and grows up, with each raid group shown horizontally? Something like:

```
G1  G2  G3
 5  10  15
 4   9  14
 3   8  13
 2   7  12
 1   6  11  ... etc
```

Use case: I like having my raid groups displayed horizontally rather than a more cubic shape, and I like to pin the raid frames near the bottom of my screen, leaving the whole top of the screen empty of UI elements.

![image](https://github.com/user-attachments/assets/bba168d9-ee38-49a5-b6ac-60bc53deb0a3)

The closest option that I can currently achieve with the pre-configured grow directions is option 4, but that displays the raid groups vertically, and grows them horizontally which is kind of the opposite of what I want, haha.

![image](https://github.com/user-attachments/assets/eabab3d0-ee23-4f6f-bb7c-c8441d5c2a0d)

Options 1 and 2 visually look like what I want, but they grow from the top down so when I am not in a group, i have a unit frame sitting in the middle of my screen instead of tucked away on top of my bottom-aligned UI.

![image](https://github.com/user-attachments/assets/a112c2c8-ab0b-46f7-9c0f-e947ab8f8173)

Perhaps out of scope, but would a more robust anchoring system be worth implementing rather than the preset grow directions? Having an anchor frame and allowing the user to define how they want the frame to expand as more units are added to the raid?

**Comment by gnwl** [comment]
Added more options. Perhaps there could be a better way to code it, it's quite copy pasty right now. But even with the way it is, a menu could be made to select "grow groups X" and "grow units Y" and whichever combination of choices a user makes sets it to these "presets". But that's making another menu, and the slider works well enough for now.

I think option 2 is the one you want now.

**Comment by karai17** [comment]
The new option 2 is exactly what I was looking for, thank you!
