### ISSUE TITLE
Suport ruRU (and other language)

### ISSUE THREAD

**Issue by gamer4eg** [gnwl/NotGrid#7]
Could you add an addon for the advanced (multilanguage) libs- to work on clients of all languages.
Also I can help with translation into Russian.

**Comment by gamer4eg** [comment]
I recommend to use the Shagu's libs

**Comment by gamer4eg** [comment]
Addon version with language support (implemented only Russian and English), it is easy to add any language, thanks to the ru community )
https://drive.google.com/open?id=0B2RWjLl8UkfxeXRUcU12RlVoalk

**Comment by gnwl** [comment]
Sorry, I've been away playing on fresh realms. Thanks for the work, I'll try to merge it soon.

**Comment by gamer4eg** [comment]
This version adds support for any language, just make only Russian (can be easily added to any other language).
Just your addon lacks the ability to turn the health band (vertically, rather than horizontally).
And remember the purpose of the possibility (as in healbot).
I apologize for the Google translator.

**Comment by gnwl** [comment]
Merged localization edits and it's working fine with the US client. There were a couple new options added that aren't translated, not sure if that poses problems for the RU client.

**Comment by gamer4eg** [comment]
Thank you very much!
By the way-you can add a function to display mana?And healers in the raid it is inconvenient to focus on the mana of each other.
