### ISSUE TITLE
Turning life strips

### ISSUE THREAD

**Issue by gamer4eg** [gnwl/NotGrid#8]
It would be nice to add a rotation option life stripes (horizontal mode)

**Comment by gnwl** [comment]
I'm not sure what this means. The only thing that's coming to mind is a texture with stripes on it but I doubt that's what you're suggesting.

**Comment by gamer4eg** [comment]
To strip health decreased horizontally rather than vertically (optional)
I apologize for the Google translator ...

**Comment by gnwl** [comment]
Added. Type in "HORIZONTAL" where its otherwise "VERTICAL" in the new orientation option in the menu.
