### ISSUE TITLE
Display mana

### ISSUE THREAD

**Issue by gamer4eg** [gnwl/NotGrid#9]
By the way-you can add a function to display mana?And healers in the raid it is inconvenient to focus on the mana of each other.

**Comment by gnwl** [comment]
Not that it would be complicated, but it was actively my intention while writing the addon to exclude mana bars and only support the "low mana"/"Mana Warning" indicator on the frame borders. Active tracking of raidwide mana (and buffs) I prefer the use of the addon RABuffs.

I won't say no to ever adding it, but it won't be soon.

**Comment by gnwl** [comment]
Added. Hurray!
